# Generated by Django 2.0 on 2018-04-08 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_issuelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
